language: go

go:
  - 1.9.2

dist: xenial
sudo: required

services:
  - docker

install:
  - sudo apt-get update
    #  - sudo apt-get install python2.7
  - if [ "$TRAVIS_BUILD_DIR" != "$GOPATH/src/github.com/a4abhishek/travis-test" ]; then
      mkdir -p $GOPATH/src/github.com/a4abhishek/;
      mv $TRAVIS_BUILD_DIR $GOPATH/src/github.com/a4abhishek;
      cd $GOPATH/src/github.com/a4abhishek/travis-test;
    fi
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.9.0/bin/darwin/amd64/kubectl
  - sudo chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl
  - curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.25.0/minikube-linux-amd64
  - sudo chmod +x minikube
  - sudo mv minikube /usr/local/bin/

script:
  - sudo minikube start --vm-driver=none --bootstrapper=localkube --kubernetes-version=v1.8.0 --feature-gates=MountPropagation=true
  - kubectl get pods --all-namespaces -o yaml
  - kubectl get svc --all-namespaces -o yaml
  - kubectl get deploy --all-namespaces -o yaml

